package common;

/**
 * Created by MechAviv on 4/3/2020.
 */
public class AdminPacketType {
    public static final int 
        CREATE = 0x0,
        REMOVE = 0x1,
        INCEXP = 0x2,
        LOGOUT = 0x3,
        BLOCK = 0x4,
        UNBLOCK = 0x5,
        NORANK = 0x6,
        SCREENSHOT = 0x7,
        DISCONNECT = 0x8,
        CENTER_BLOCK = 0x9,
        PORTAL = 0xA,
        NPCVAR = 0xB,
        NPCVAR_SET = 0xC,
        NPCVAR_GET = 0xD,
        BANISH_ALL = 0xE,
        TIMER = 0xF,
        DESC = 0x10,
        EVENT_START = 0x11,
        HIDE = 0x12,
        USERLIST = 0x13,
        SENDUSER = 0x14,
        ENTRUSTEDSHOP = 0x15,
        ADMINEVENT = 0x16,
        KILL_MOB = 0x17,
        QUEST_SET = 0x18,
        QUEST_RESET = 0x19,
        HACKCHECKCOUNTRELOAD = 0x1A,
        QUEST = 0x1B,
        SUMMON = 0x1C,
        MOB_HP = 0x1D,
        LEVEL_SET = 0x1E,
        JOB_SET = 0x1F,
        NOCOOLTIME = 0x20,
        APGET = 0x21,
        SPGET = 0x22,
        STR = 0x23,
        DEX = 0x24,
        INT = 0x25,
        LUK = 0x26,
        SKILL = 0x27,
        MMON = 0x28,
        MMOFF = 0x29,
        SNOW = 0x2A,
        WARN = 0x2B,
        LOG = 0x2C,
        RESETMAP = 0x2D,
        FREEMARKETCLIP = 0x2E,
        DESTROYSHOP = 0x2F,
        SETOBJECTSTATE = 0x30,
        SHOWRANK = 0x31,
        FORBIDDENMAPRELOAD = 0x32,
        CRISP = 0x33,
        GACHAPONBOXRELOAD = 0x34,
        GACHAPONRELOAD = 0x35,
        WEATHEREVENTRELOAD = 0x36,
        REWORDRELOAD = 0x37,
        CAKEPIERELOAD = 0x38,
        GMBOARDRELOAD = 0x39,
        PQANSWER = 0x3A,
        MOBCONTROL = 0x3B,
        PASSIVESKILLVALUEVIEW = 0x3C,
        PASSIVESKILLSET = 0x3D,
        PASSIVESKILLUPDATE = 0x3E,
        GETCOOLTIME = 0x3F,
        FIELDUSERCOUNTLIMIT = 0x40,
        SERVEROPTRELOAD = 0x41,
        STAGECHANGE = 0x42,
        ACTIVATESTAGECHANGE = 0x43,
        RELOADGACHAPONBONUS = 0x44,
        RELOADVISITORLOGINFO = 0x45,
        CUBECOMPLETE = 0x46,
        PARTYCHECK = 0x47,
        RELOADDISALLOWEDDELIVERYQUEST = 0x48;
}
